[llm]
provider = "deepseek"
model_name = "deepseek-chat"
api_key = ""

[embedding]
provider = "huggingface"
#model_name = "BAAI/bge-small-zh-v1.5"
model_name = "sentence-transformers/all-mpnet-base-v2"

[langsmith]
tracing = false
api_key = ""
project = "default"

[external_resource]
image_net = "https://github.com/towhee-io/examples/releases/download/data/reverse_image_search.zip"
