[llm]
provider = "deepseek"
model_name = "deepseek-chat"
api_key = ""

[embedding]
provider = "huggingface"
model_name = "BAAI/bge-small-zh-v1.5"
#model_name = "sentence-transformers/all-mpnet-base-v2"
